# Generated by Django 4.0.5 on 2022-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mydiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=5000)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
