# Generated by Django 4.0.5 on 2022-10-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydiary',
            name='datetime',
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=54)),
                ('pass1', models.IntegerField()),
                ('pass2', models.IntegerField()),
                ('book_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.mydiary')),
            ],
        ),
    ]
