# Generated by Django 4.1.4 on 2023-02-24 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_remove_mydiary_datetime_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user",
        ),
    ]
