# Generated by Django 4.1.4 on 2023-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mydiary",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
